FROM rust:1.66-slim-buster

WORKDIR /app

RUN apt-get update && apt-get -y install zip libssl-dev pkg-config
RUN apt-get -y install python3 python3-pip
RUN pip3 install minio
RUN cargo init .

COPY Cargo.* ./

RUN cargo test --release --no-run

COPY . .
RUN chmod +x ./TESTING/run_tests.sh

CMD ["./TESTING/run_tests.sh"]
